site_name: Our Writings
site_description: A place for our latest thinking and a record of our previous thoughts
site_url: https://zeroth.tech/blogs

nav:
  - Tags: tags.md

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: images/Zerothlogo_white0.svg
  features:
    - navigation.instant
    - navigation.indexes
  palette:
    - scheme: default 
      primary: light blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    tag:
      supply: octicons/package-dependents-16
      token: fontawesome/solid/coins

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zeroth-tech
  tags:
    supply chain: supply
    tokenization: token
  

plugins:
  - search:
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: true
      post_dir: "./posts"
      post_url_max_categories: 1
      post_url_format: "{date}/{slug}"
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_toc: false
      categories: true
      categories_name: Categories
      categories_slugify_separator: "-"
      categories_toc: false
      authors: true
      authors_file: ".authors.yml"
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: false
  - tags:
      enabled: true
      tags: true
      tags_file: tags.md


copyright: Copyright &copy; 2024 Zeroth Technology, Inc. All rights reserved.