authors:
  jamescbury:
    name: Jamey Canterbury
    description: Creator
    avatar: https://github.com/jamescbury.png
    url: https://twitter.com/intent/follow?screen_name=jamescbury
  ankmister:
    name: Ankur Garg
    description: Creator
    avatar: https://github.com/ankmister.png
    url: https://twitter.com/intent/follow?screen_name=ankmister
  patmac:
    name: Patrick Macom
    description: Creator
    avatar: https://github.com/patmacs.png
    url: https://twitter.com/intent/follow?screen_name=patmacs